resource_types:
  - name: registry-image-dev
    type: registry-image
    source:
      repository: concourse/registry-image-resource
      tag: dev

  - name: pull-request
    type: registry-image-dev
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: golang
    type: registry-image-dev
    source:
      repository: golang
      tag: 1.18-stretch

  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: ((git-webhook-pr-wings-secret))
    source:
      repository: cloudfoundry-incubator/notifications
      access_token: ((git-toronto-ci-access-token))

jobs:
  - name: run-tests
    public: true
    plan:
      - get: pull-request
        trigger: true
      - get: golang
      - task: run
        params:
          DATABASE_HOST: localhost
          DATABASE_USER: notifications
          DATABASE_PASSWORD: password
          DATABASE_NAME: notifications_test
        image: golang
        config:
          platform: linux
          inputs:
            - name: pull-request
              path: go/src/github.com/cloudfoundry-incubator/notifications
          run:
            path: /bin/bash
            args:
              - -c
              - |
                echo "=== Setting up Go ==="
                export GOPATH=`pwd`/go
                export PATH=$PATH:$GOPATH/bin

                export GO111MODULE=off
                go get github.com/onsi/ginkgo/ginkgo
                export GO111MODULE=on
                export GOFLAGS=-mod=vendor

                cd go/src/github.com/cloudfoundry-incubator/notifications
                go version

                export GOFLAGS=-mod=vendor

                echo "=== Setting up MySQL ==="
                apt-get -qqy update
                apt-get install -qqy mysql-server

                mysqld --version
                service mysql start

                mysql -uroot -e "CREATE USER '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';"
                mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO '${DATABASE_USER}'@'localhost';"
                mysql -uroot -e "UPDATE mysql.user SET authentication_string=PASSWORD('${DATABASE_PASSWORD}'), plugin='mysql_native_password' WHERE user='${DATABASE_USER}';"
                mysql -uroot -e "CREATE DATABASE ${DATABASE_NAME};"
                mysql -uroot -e "FLUSH PRIVILEGES;"

                echo "=== Running Tests ==="
                export DATABASE_URL="$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:3306/$DATABASE_NAME"

                ./bin/test
                EXIT_CODE=$?

                service mysql stop

                if [[ $EXIT_CODE != 0 ]]; then
                  exit $EXIT_CODE
                fi

                if [[ -n "`git status --porcelain`" ]]; then
                  echo "Detected a git diff"
                  git status --porcelain
                  exit 1
                fi
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success
