FORMAT: 1A

# Notifications API
This is version 2 of the Cloud Foundry notifications API. Integrate with this API in order to send messages to developers and billing contacts in your CF deployment.

## Authorization Tokens
See [here](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-Tokens.md) for more information about UAA tokens.



# Group Campaign types
Some description of the Campaign types

## Campaign type List [/campaign_types]



### POST Campaign types [POST]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTEsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.cjzRtmI2f0wW4ZE4JzvfvaPXRsWT7mHKk9QGvNXG1UOnh1m7Ayu-7yhRIlN3NXoGZXp6redn13qjYTRGJf71_UtssN_L6G5f9o1rsg66ajW7MArheirbofdmoesHmbvQXY1Wq3HtF_oOZRdbZvzx_Lzb0lPTg_SmKHiSxuqvqbW_ajq8rRuIKTtbyaZpENaEqXkAlq7qTn2bdUKvjg1WEGwtBI4jnAHWh4H2eUutt7wk3MaFvlUkNPlps70kJ3ksTX2X3Ms8KSCuDUcgNbplNzlFLWA_xbeKCAqOe7K4T63e6nq3-mwgQv6u_6WmagvW29zQTePkLm5kX-McvMEKkA



            X-Notifications-Version: 2



    + Body

            {"description":"a great campaign type","name":"some-campaign-type"}


+ Response 201

    + Headers



            Content-Length: 228



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:11 GMT



    + Body

            {"id":"d3a0486b-f774-592e-0df5-df0cbdfafade","name":"some-campaign-type","description":"a great campaign type","critical":false,"template_id":"","_links":{"self":{"href":"/campaign_types/d3a0486b-f774-592e-0df5-df0cbdfafade"}}}





### GET Campaign types [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTEsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.cjzRtmI2f0wW4ZE4JzvfvaPXRsWT7mHKk9QGvNXG1UOnh1m7Ayu-7yhRIlN3NXoGZXp6redn13qjYTRGJf71_UtssN_L6G5f9o1rsg66ajW7MArheirbofdmoesHmbvQXY1Wq3HtF_oOZRdbZvzx_Lzb0lPTg_SmKHiSxuqvqbW_ajq8rRuIKTtbyaZpENaEqXkAlq7qTn2bdUKvjg1WEGwtBI4jnAHWh4H2eUutt7wk3MaFvlUkNPlps70kJ3ksTX2X3Ms8KSCuDUcgNbplNzlFLWA_xbeKCAqOe7K4T63e6nq3-mwgQv6u_6WmagvW29zQTePkLm5kX-McvMEKkA



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 405



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:11 GMT



    + Body

            {"campaign_types":[{"id":"d3a0486b-f774-592e-0df5-df0cbdfafade","name":"some-campaign-type","description":"a great campaign type","critical":false,"template_id":"","_links":{"self":{"href":"/campaign_types/d3a0486b-f774-592e-0df5-df0cbdfafade"}}}],"_links":{"self":{"href":"/senders/4676b282-606c-53b1-42ac-14cc7fd46754/campaign_types"},"sender":{"href":"/senders/4676b282-606c-53b1-42ac-14cc7fd46754"}}}





## Campaign type [/campaign_types/{id}]

+ Parameters

	+ id: `68a5sdf67` (required, string) - The Campaign type ID



### GET Campaign type [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTEsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.cjzRtmI2f0wW4ZE4JzvfvaPXRsWT7mHKk9QGvNXG1UOnh1m7Ayu-7yhRIlN3NXoGZXp6redn13qjYTRGJf71_UtssN_L6G5f9o1rsg66ajW7MArheirbofdmoesHmbvQXY1Wq3HtF_oOZRdbZvzx_Lzb0lPTg_SmKHiSxuqvqbW_ajq8rRuIKTtbyaZpENaEqXkAlq7qTn2bdUKvjg1WEGwtBI4jnAHWh4H2eUutt7wk3MaFvlUkNPlps70kJ3ksTX2X3Ms8KSCuDUcgNbplNzlFLWA_xbeKCAqOe7K4T63e6nq3-mwgQv6u_6WmagvW29zQTePkLm5kX-McvMEKkA



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 228



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:11 GMT



    + Body

            {"id":"d3a0486b-f774-592e-0df5-df0cbdfafade","name":"some-campaign-type","description":"a great campaign type","critical":false,"template_id":"","_links":{"self":{"href":"/campaign_types/d3a0486b-f774-592e-0df5-df0cbdfafade"}}}





### PUT Campaign type [PUT]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTEsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.cjzRtmI2f0wW4ZE4JzvfvaPXRsWT7mHKk9QGvNXG1UOnh1m7Ayu-7yhRIlN3NXoGZXp6redn13qjYTRGJf71_UtssN_L6G5f9o1rsg66ajW7MArheirbofdmoesHmbvQXY1Wq3HtF_oOZRdbZvzx_Lzb0lPTg_SmKHiSxuqvqbW_ajq8rRuIKTtbyaZpENaEqXkAlq7qTn2bdUKvjg1WEGwtBI4jnAHWh4H2eUutt7wk3MaFvlUkNPlps70kJ3ksTX2X3Ms8KSCuDUcgNbplNzlFLWA_xbeKCAqOe7K4T63e6nq3-mwgQv6u_6WmagvW29zQTePkLm5kX-McvMEKkA



            X-Notifications-Version: 2



    + Body

            {"critical":true,"description":"still the same great campaign type","name":"updated-campaign-type","template_id":"3fae7814-c497-f060-560b-44fb252eeaa6"}


+ Response 200

    + Headers



            Content-Length: 279



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:11 GMT



    + Body

            {"id":"d3a0486b-f774-592e-0df5-df0cbdfafade","name":"updated-campaign-type","description":"still the same great campaign type","critical":true,"template_id":"3fae7814-c497-f060-560b-44fb252eeaa6","_links":{"self":{"href":"/campaign_types/d3a0486b-f774-592e-0df5-df0cbdfafade"}}}





### DELETE Campaign type [DELETE]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTEsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.cjzRtmI2f0wW4ZE4JzvfvaPXRsWT7mHKk9QGvNXG1UOnh1m7Ayu-7yhRIlN3NXoGZXp6redn13qjYTRGJf71_UtssN_L6G5f9o1rsg66ajW7MArheirbofdmoesHmbvQXY1Wq3HtF_oOZRdbZvzx_Lzb0lPTg_SmKHiSxuqvqbW_ajq8rRuIKTtbyaZpENaEqXkAlq7qTn2bdUKvjg1WEGwtBI4jnAHWh4H2eUutt7wk3MaFvlUkNPlps70kJ3ksTX2X3Ms8KSCuDUcgNbplNzlFLWA_xbeKCAqOe7K4T63e6nq3-mwgQv6u_6WmagvW29zQTePkLm5kX-McvMEKkA



            X-Notifications-Version: 2



    + Body

            


+ Response 204

    + Headers



            Date: Mon, 05 Oct 2015 20:43:11 GMT



    + Body

            






# Group Campaigns
Some description of the Campaigns

## Campaign List [/campaigns]



### POST Campaigns [POST]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.Ml-K4f_Wb9LhNqtZu0pNha8GAS1QSJDIiNh-3Ftqb5fOvAoBjexJzry7OWmWKo0WCt199AM4GtUTEdwFzBQZgqavvkOmCvS6KAcwdbFVPllzbOOOqn-_eMe0VZfeR8ydFZ0fQQVgzP8pei02EX5AEQ6vDKhhRqh7Wk5qT8iFhMBBBmcGF99JAtP4xEVSBsOgqWCkG_ZEpoT0Zk382RaD7XlsX9MgUMEam_Cd3Esh4th63HTuk8aNk3dsrrFuRhROwM13X5G8lsSlOd7XhjWOig5a803yF97Go2ocYN3zOOrsuiYuNurCHt2kj4O59zYCPFlB7ymXOuX9BtJNmr_Svg



            X-Notifications-Version: 2



    + Body

            {"campaign_type_id":"b8c4cc80-b2b2-a408-62c1-d5fdec9a7cc8","reply_to":"no-reply@example.com","send_to":{"email":"test@example.com"},"subject":"campaign subject","template_id":"d635e639-493e-bf65-710f-4aadd7965915","text":"campaign body"}


+ Response 202

    + Headers



            Content-Length: 593



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:12 GMT



    + Body

            {"_links":{"campaign_type":{"href":"/campaign_types/b8c4cc80-b2b2-a408-62c1-d5fdec9a7cc8"},"self":{"href":"/campaigns/68e07344-e4af-2dbd-d3bb-6f3627886e62"},"status":{"href":"/campaigns/68e07344-e4af-2dbd-d3bb-6f3627886e62/status"},"template":{"href":"/templates/d635e639-493e-bf65-710f-4aadd7965915"}},"campaign_type_id":"b8c4cc80-b2b2-a408-62c1-d5fdec9a7cc8","html":"","id":"68e07344-e4af-2dbd-d3bb-6f3627886e62","reply_to":"no-reply@example.com","send_to":{"email":"test@example.com"},"subject":"campaign subject","template_id":"d635e639-493e-bf65-710f-4aadd7965915","text":"campaign body"}




## Campaign [/campaigns/{id}]

+ Parameters

	+ id: `68a5sdf67` (required, string) - The Campaign ID



### GET Campaign [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.Ml-K4f_Wb9LhNqtZu0pNha8GAS1QSJDIiNh-3Ftqb5fOvAoBjexJzry7OWmWKo0WCt199AM4GtUTEdwFzBQZgqavvkOmCvS6KAcwdbFVPllzbOOOqn-_eMe0VZfeR8ydFZ0fQQVgzP8pei02EX5AEQ6vDKhhRqh7Wk5qT8iFhMBBBmcGF99JAtP4xEVSBsOgqWCkG_ZEpoT0Zk382RaD7XlsX9MgUMEam_Cd3Esh4th63HTuk8aNk3dsrrFuRhROwM13X5G8lsSlOd7XhjWOig5a803yF97Go2ocYN3zOOrsuiYuNurCHt2kj4O59zYCPFlB7ymXOuX9BtJNmr_Svg



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 593



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:12 GMT



    + Body

            {"_links":{"campaign_type":{"href":"/campaign_types/b8c4cc80-b2b2-a408-62c1-d5fdec9a7cc8"},"self":{"href":"/campaigns/68e07344-e4af-2dbd-d3bb-6f3627886e62"},"status":{"href":"/campaigns/68e07344-e4af-2dbd-d3bb-6f3627886e62/status"},"template":{"href":"/templates/d635e639-493e-bf65-710f-4aadd7965915"}},"campaign_type_id":"b8c4cc80-b2b2-a408-62c1-d5fdec9a7cc8","html":"","id":"68e07344-e4af-2dbd-d3bb-6f3627886e62","reply_to":"no-reply@example.com","send_to":{"email":"test@example.com"},"subject":"campaign subject","template_id":"d635e639-493e-bf65-710f-4aadd7965915","text":"campaign body"}






# Group Info
Some description of the Info

## Inf List [/info]



### GET Info [GET]


+ Request

    Required scopes:
    ```no-highlight
    
    ```

    + Headers



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 13



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:11 GMT



    + Body

            {"version":2}




## Inf [/info/{id}]

+ Parameters

	+ id: `68a5sdf67` (required, string) - The Inf ID





# Group Senders
Some description of the Senders

## Sender List [/senders]



### POST Senders [POST]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.Ml-K4f_Wb9LhNqtZu0pNha8GAS1QSJDIiNh-3Ftqb5fOvAoBjexJzry7OWmWKo0WCt199AM4GtUTEdwFzBQZgqavvkOmCvS6KAcwdbFVPllzbOOOqn-_eMe0VZfeR8ydFZ0fQQVgzP8pei02EX5AEQ6vDKhhRqh7Wk5qT8iFhMBBBmcGF99JAtP4xEVSBsOgqWCkG_ZEpoT0Zk382RaD7XlsX9MgUMEam_Cd3Esh4th63HTuk8aNk3dsrrFuRhROwM13X5G8lsSlOd7XhjWOig5a803yF97Go2ocYN3zOOrsuiYuNurCHt2kj4O59zYCPFlB7ymXOuX9BtJNmr_Svg



            X-Notifications-Version: 2



    + Body

            {"name":"My Cool App"}


+ Response 201

    + Headers



            Content-Length: 310



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:12 GMT



    + Body

            {"id":"beeadffa-e78b-b8d3-7983-ac619e1d6af7","name":"My Cool App","_links":{"self":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7"},"campaign_types":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaign_types"},"campaigns":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaigns"}}}





### GET Senders [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.Ml-K4f_Wb9LhNqtZu0pNha8GAS1QSJDIiNh-3Ftqb5fOvAoBjexJzry7OWmWKo0WCt199AM4GtUTEdwFzBQZgqavvkOmCvS6KAcwdbFVPllzbOOOqn-_eMe0VZfeR8ydFZ0fQQVgzP8pei02EX5AEQ6vDKhhRqh7Wk5qT8iFhMBBBmcGF99JAtP4xEVSBsOgqWCkG_ZEpoT0Zk382RaD7XlsX9MgUMEam_Cd3Esh4th63HTuk8aNk3dsrrFuRhROwM13X5G8lsSlOd7XhjWOig5a803yF97Go2ocYN3zOOrsuiYuNurCHt2kj4O59zYCPFlB7ymXOuX9BtJNmr_Svg



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 362



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:12 GMT



    + Body

            {"senders":[{"id":"beeadffa-e78b-b8d3-7983-ac619e1d6af7","name":"My Cool App","_links":{"self":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7"},"campaign_types":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaign_types"},"campaigns":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaigns"}}}],"_links":{"self":{"href":"/senders"}}}





## Sender [/senders/{id}]

+ Parameters

	+ id: `68a5sdf67` (required, string) - The Sender ID



### DELETE Sender [DELETE]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTAsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.QhXlaIYG4Abdm8HgTkcSux5sPiTrPksXtsLnBQGcs6sZ4vtvsolRQa5O6sncyJAN4-qURfxzAMbUiMFk0QBJx1uUpSn_sNawf9ZD1Q4jRcIltv9Gcy9yXmUxZ0pA7rnskHfWX7rMWzNdLhoArbwZQhcLtTZ3pWTvAdjFrfCehmDxJ_nyWkM2OrlKlRV9KGKl5JeMOOBb_wpewIKI66k_D6A9wXv_c0xk8YqBHujisaBao9ZnO2Kb9BygIDairvgtp9UK1KhNSULbcUBF47okHQsaIxlTC3J5d1z0XYJfILeoT20_5bRq2Fdoob9NZw6H0CYZmfynYOei-UUz4XVwxw



            X-Notifications-Version: 2



    + Body

            


+ Response 204

    + Headers



            Date: Mon, 05 Oct 2015 20:43:10 GMT



    + Body

            




### GET Sender [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.Ml-K4f_Wb9LhNqtZu0pNha8GAS1QSJDIiNh-3Ftqb5fOvAoBjexJzry7OWmWKo0WCt199AM4GtUTEdwFzBQZgqavvkOmCvS6KAcwdbFVPllzbOOOqn-_eMe0VZfeR8ydFZ0fQQVgzP8pei02EX5AEQ6vDKhhRqh7Wk5qT8iFhMBBBmcGF99JAtP4xEVSBsOgqWCkG_ZEpoT0Zk382RaD7XlsX9MgUMEam_Cd3Esh4th63HTuk8aNk3dsrrFuRhROwM13X5G8lsSlOd7XhjWOig5a803yF97Go2ocYN3zOOrsuiYuNurCHt2kj4O59zYCPFlB7ymXOuX9BtJNmr_Svg



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 310



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:12 GMT



    + Body

            {"id":"beeadffa-e78b-b8d3-7983-ac619e1d6af7","name":"My Cool App","_links":{"self":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7"},"campaign_types":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaign_types"},"campaigns":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaigns"}}}





### PUT Sender [PUT]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.Ml-K4f_Wb9LhNqtZu0pNha8GAS1QSJDIiNh-3Ftqb5fOvAoBjexJzry7OWmWKo0WCt199AM4GtUTEdwFzBQZgqavvkOmCvS6KAcwdbFVPllzbOOOqn-_eMe0VZfeR8ydFZ0fQQVgzP8pei02EX5AEQ6vDKhhRqh7Wk5qT8iFhMBBBmcGF99JAtP4xEVSBsOgqWCkG_ZEpoT0Zk382RaD7XlsX9MgUMEam_Cd3Esh4th63HTuk8aNk3dsrrFuRhROwM13X5G8lsSlOd7XhjWOig5a803yF97Go2ocYN3zOOrsuiYuNurCHt2kj4O59zYCPFlB7ymXOuX9BtJNmr_Svg



            X-Notifications-Version: 2



    + Body

            {"name":"My Not Cool App"}


+ Response 200

    + Headers



            Content-Length: 314



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:12 GMT



    + Body

            {"id":"beeadffa-e78b-b8d3-7983-ac619e1d6af7","name":"My Not Cool App","_links":{"self":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7"},"campaign_types":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaign_types"},"campaigns":{"href":"/senders/beeadffa-e78b-b8d3-7983-ac619e1d6af7/campaigns"}}}







# Group Templates
Some description of the Templates

## Template List [/templates]



### POST Templates [POST]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTAsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.QhXlaIYG4Abdm8HgTkcSux5sPiTrPksXtsLnBQGcs6sZ4vtvsolRQa5O6sncyJAN4-qURfxzAMbUiMFk0QBJx1uUpSn_sNawf9ZD1Q4jRcIltv9Gcy9yXmUxZ0pA7rnskHfWX7rMWzNdLhoArbwZQhcLtTZ3pWTvAdjFrfCehmDxJ_nyWkM2OrlKlRV9KGKl5JeMOOBb_wpewIKI66k_D6A9wXv_c0xk8YqBHujisaBao9ZnO2Kb9BygIDairvgtp9UK1KhNSULbcUBF47okHQsaIxlTC3J5d1z0XYJfILeoT20_5bRq2Fdoob9NZw6H0CYZmfynYOei-UUz4XVwxw



            X-Notifications-Version: 2



    + Body

            {"html":"template html","metadata":{"template":"metadata"},"name":"An interesting template","subject":"template subject","text":"template text"}


+ Response 201

    + Headers



            Content-Length: 266



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:10 GMT



    + Body

            {"id":"135c1ad0-9037-2749-3fe5-992f3cc1188a","name":"An interesting template","text":"template text","html":"template html","subject":"template subject","metadata":{"template":"metadata"},"_links":{"self":{"href":"/templates/135c1ad0-9037-2749-3fe5-992f3cc1188a"}}}





### GET Templates [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTAsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.QhXlaIYG4Abdm8HgTkcSux5sPiTrPksXtsLnBQGcs6sZ4vtvsolRQa5O6sncyJAN4-qURfxzAMbUiMFk0QBJx1uUpSn_sNawf9ZD1Q4jRcIltv9Gcy9yXmUxZ0pA7rnskHfWX7rMWzNdLhoArbwZQhcLtTZ3pWTvAdjFrfCehmDxJ_nyWkM2OrlKlRV9KGKl5JeMOOBb_wpewIKI66k_D6A9wXv_c0xk8YqBHujisaBao9ZnO2Kb9BygIDairvgtp9UK1KhNSULbcUBF47okHQsaIxlTC3J5d1z0XYJfILeoT20_5bRq2Fdoob9NZw6H0CYZmfynYOei-UUz4XVwxw



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 298



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:10 GMT



    + Body

            {"templates":[{"id":"135c1ad0-9037-2749-3fe5-992f3cc1188a","name":"A more interesting template","text":"text","html":"html","subject":"subject","metadata":{"banana":"something"},"_links":{"self":{"href":"/templates/135c1ad0-9037-2749-3fe5-992f3cc1188a"}}}],"_links":{"self":{"href":"/templates"}}}





## Template [/templates/{id}]

+ Parameters

	+ id: `68a5sdf67` (required, string) - The Template ID



### GET Template [GET]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTAsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.QhXlaIYG4Abdm8HgTkcSux5sPiTrPksXtsLnBQGcs6sZ4vtvsolRQa5O6sncyJAN4-qURfxzAMbUiMFk0QBJx1uUpSn_sNawf9ZD1Q4jRcIltv9Gcy9yXmUxZ0pA7rnskHfWX7rMWzNdLhoArbwZQhcLtTZ3pWTvAdjFrfCehmDxJ_nyWkM2OrlKlRV9KGKl5JeMOOBb_wpewIKI66k_D6A9wXv_c0xk8YqBHujisaBao9ZnO2Kb9BygIDairvgtp9UK1KhNSULbcUBF47okHQsaIxlTC3J5d1z0XYJfILeoT20_5bRq2Fdoob9NZw6H0CYZmfynYOei-UUz4XVwxw



            X-Notifications-Version: 2



    + Body

            


+ Response 200

    + Headers



            Content-Length: 266



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:10 GMT



    + Body

            {"id":"135c1ad0-9037-2749-3fe5-992f3cc1188a","name":"An interesting template","text":"template text","html":"template html","subject":"template subject","metadata":{"template":"metadata"},"_links":{"self":{"href":"/templates/135c1ad0-9037-2749-3fe5-992f3cc1188a"}}}





### PUT Template [PUT]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTAsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.QhXlaIYG4Abdm8HgTkcSux5sPiTrPksXtsLnBQGcs6sZ4vtvsolRQa5O6sncyJAN4-qURfxzAMbUiMFk0QBJx1uUpSn_sNawf9ZD1Q4jRcIltv9Gcy9yXmUxZ0pA7rnskHfWX7rMWzNdLhoArbwZQhcLtTZ3pWTvAdjFrfCehmDxJ_nyWkM2OrlKlRV9KGKl5JeMOOBb_wpewIKI66k_D6A9wXv_c0xk8YqBHujisaBao9ZnO2Kb9BygIDairvgtp9UK1KhNSULbcUBF47okHQsaIxlTC3J5d1z0XYJfILeoT20_5bRq2Fdoob9NZw6H0CYZmfynYOei-UUz4XVwxw



            X-Notifications-Version: 2



    + Body

            {"html":"html","metadata":{"banana":"something"},"name":"A more interesting template","subject":"subject","text":"text"}


+ Response 200

    + Headers



            Content-Length: 242



            Content-Type: text/plain; charset=utf-8



            Date: Mon, 05 Oct 2015 20:43:10 GMT



    + Body

            {"id":"135c1ad0-9037-2749-3fe5-992f3cc1188a","name":"A more interesting template","text":"text","html":"html","subject":"subject","metadata":{"banana":"something"},"_links":{"self":{"href":"/templates/135c1ad0-9037-2749-3fe5-992f3cc1188a"}}}





### DELETE Template [DELETE]


+ Request

    Required scopes:
    ```no-highlight
     notifications.manage notifications.write emails.write notification_preferences.admin critical_notifications.write notification_templates.admin notification_templates.write notification_templates.read
    ```

    + Headers



            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJteS1jbGllbnQiLCJleHAiOjE0NDQzMzY5OTAsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMDUvb2F1dGgvdG9rZW4iLCJzY29wZSI6WyJub3RpZmljYXRpb25zLm1hbmFnZSIsIm5vdGlmaWNhdGlvbnMud3JpdGUiLCJlbWFpbHMud3JpdGUiLCJub3RpZmljYXRpb25fcHJlZmVyZW5jZXMuYWRtaW4iLCJjcml0aWNhbF9ub3RpZmljYXRpb25zLndyaXRlIiwibm90aWZpY2F0aW9uX3RlbXBsYXRlcy5hZG1pbiIsIm5vdGlmaWNhdGlvbl90ZW1wbGF0ZXMud3JpdGUiLCJub3RpZmljYXRpb25fdGVtcGxhdGVzLnJlYWQiXX0.QhXlaIYG4Abdm8HgTkcSux5sPiTrPksXtsLnBQGcs6sZ4vtvsolRQa5O6sncyJAN4-qURfxzAMbUiMFk0QBJx1uUpSn_sNawf9ZD1Q4jRcIltv9Gcy9yXmUxZ0pA7rnskHfWX7rMWzNdLhoArbwZQhcLtTZ3pWTvAdjFrfCehmDxJ_nyWkM2OrlKlRV9KGKl5JeMOOBb_wpewIKI66k_D6A9wXv_c0xk8YqBHujisaBao9ZnO2Kb9BygIDairvgtp9UK1KhNSULbcUBF47okHQsaIxlTC3J5d1z0XYJfILeoT20_5bRq2Fdoob9NZw6H0CYZmfynYOei-UUz4XVwxw



            X-Notifications-Version: 2



    + Body

            


+ Response 204

    + Headers



            Date: Mon, 05 Oct 2015 20:43:10 GMT



    + Body

            





